# Generated by Django 4.0.6 on 2022-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/contacts/%Y')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('birthday', models.DateField(blank=True, default='1900-10-10')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['date_created', 'phone'],
            },
        ),
    ]
